/**
 * 🌿 Монгол Улсын 21 аймгийн өгөгдлийг MongoDB-д оруулах
 *
 * Ажиллуулах:
 *   node scripts/seed-aimags.mjs
 */

import { MongoClient } from 'mongodb';

const MONGODB_URI = 'mongodb+srv://zenitht19:***REMOVED***@cluster0.wietegr.mongodb.net/mng-resorts?retryWrites=true&w=majority';
const DB_NAME = 'mng-resorts';

const aimags = [
  {
    name: 'Архангай аймаг',
    type: 'nature',
    description: 'Архангай аймаг нь Монгол Улсын төв хэсэгт оршдог бөгөөд Хангайн нуруу, Тэрхийн Цагаан нуур, Цэцэрлэгийн хот зэрэг үзэсгэлэнт газруудаараа алдартай. Ой тайга, нуур цөөрөм, халуун рашааны газруудаар баялаг аймаг.',
    short_desc: 'Хангайн нуруу, Тэрхийн Цагаан нуур, байгалийн үзэсгэлэнт аймаг',
    province: 'Архангай',
    address: 'Цэцэрлэг хот, Архангай аймаг',
    latitude: 47.4769,
    longitude: 101.4611,
    cover_image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    is_published: true,
    is_featured: true,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Баян-Өлгий аймаг',
    type: 'nature',
    description: 'Баян-Өлгий аймаг нь Монгол Улсын баруун өнцөгт, Алтайн нурууны тэвэрт оршдог. Казах угсааны иргэд голлон суурьшсан энэ аймаг нь бүргэдээр ан хийх уламжлалт соёл, Алтайн мөнхийн цаст оргилуудаараа дэлхий нийтэд танигдсан.',
    short_desc: 'Алтайн нуруу, бүргэдчин соёл, Казах угсааны нутаг',
    province: 'Баян-Өлгий',
    address: 'Өлгий хот, Баян-Өлгий аймаг',
    latitude: 48.9686,
    longitude: 89.9632,
    cover_image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    is_published: true,
    is_featured: true,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Баянхонгор аймаг',
    type: 'nature',
    description: 'Баянхонгор аймаг нь Монгол Улсын өмнөд хэсэгт оршдог бөгөөд говь, хээр, уулын ландшафт хосолдог онцлогтой. Их Богд уул, Шаргын говь, Бичигт хад зэрэг байгалийн гайхамшгуудаар баялаг.',
    short_desc: 'Говь, уул, хээр хосолсон өвөрмөц байгалийн аймаг',
    province: 'Баянхонгор',
    address: 'Баянхонгор хот, Баянхонгор аймаг',
    latitude: 46.1944,
    longitude: 100.7181,
    cover_image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800',
    is_published: true,
    is_featured: false,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Булган аймаг',
    type: 'nature',
    description: 'Булган аймаг нь Монгол Улсын умард хэсэгт оршдог бөгөөд ой тайга, нугын газар нутгаараа онцлогтой. Булган голын хөндий, Хутаг-Өндөр сумын ойн газрууд нь аялал жуулчлалд тохиромжтой.',
    short_desc: 'Ой тайга, нуга, Булган голын хөндий',
    province: 'Булган',
    address: 'Булган хот, Булган аймаг',
    latitude: 48.8145,
    longitude: 103.5338,
    cover_image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
    is_published: true,
    is_featured: false,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Говь-Алтай аймаг',
    type: 'nature',
    description: 'Говь-Алтай аймаг нь Монгол Алтайн баруун урд хэсэгт оршдог. Монгол Алтайн Цаадах Говь дархан цаазат газар, Хасагт Хайрхан уул, Эхийн голын хөтлийн байгалийн цогцолбор зэрэг өвөрмөц газруудтай.',
    short_desc: 'Монгол Алтай, говийн байгалийн гайхамшгууд',
    province: 'Говь-Алтай',
    address: 'Алтай хот, Говь-Алтай аймаг',
    latitude: 45.7625,
    longitude: 96.2836,
    cover_image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
    is_published: true,
    is_featured: false,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Говьсүмбэр аймаг',
    type: 'nature',
    description: 'Говьсүмбэр аймаг нь Монгол Улсын хамгийн жижиг аймаг бөгөөд Дундговь, Дорноговь, Хэнтий аймгуудтай хиллэдэг. Чойр хот нь аймгийн төв бөгөөд цөлийн тал хээрийн өвөрмөц байгалитай.',
    short_desc: 'Цөл, хээр, тал газрын өвөрмөц аймаг',
    province: 'Говьсүмбэр',
    address: 'Чойр хот, Говьсүмбэр аймаг',
    latitude: 46.4764,
    longitude: 108.5569,
    cover_image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800',
    is_published: true,
    is_featured: false,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Дархан-Уул аймаг',
    type: 'nature',
    description: 'Дархан-Уул аймаг нь Монгол Улсын хоёрдугаар том хот Дархантай бөгөөд аж үйлдвэрийн төвөөр алдартай. Харааны голын хөндий, ойн газрууд нь байгалийн аялалд тохиромжтой.',
    short_desc: 'Дархан хот, Харааны голын хөндий, ойн аялал',
    province: 'Дархан-Уул',
    address: 'Дархан хот, Дархан-Уул аймаг',
    latitude: 49.4667,
    longitude: 105.9667,
    cover_image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800',
    is_published: true,
    is_featured: false,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Дорноговь аймаг',
    type: 'nature',
    description: 'Дорноговь аймаг нь Зүүн Говийн нэрээр алдартай бөгөөд Монгол Улсын өмнөд зүгт оршдог. Хамрын хийд, Халзан уул, Замын-Үүд дэх Хятад-Монголын хилийн боомт зэрэг газруудаар алдартай.',
    short_desc: 'Зүүн говь, Хамрын хийд, хилийн боомт',
    province: 'Дорноговь',
    address: 'Сайншанд хот, Дорноговь аймаг',
    latitude: 44.8917,
    longitude: 110.1283,
    cover_image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800',
    is_published: true,
    is_featured: false,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Дорнод аймаг',
    type: 'nature',
    description: 'Дорнод аймаг нь Монгол Улсын зүүн хязгаарт оршдог бөгөөд Халхын гол, Буйр нуур, Монгол Дагуурын тал хээр зэрэг онцгой байгалийн газруудтай. Мотоциклоор тал хээрийн аялал хийхэд хамгийн тохиромжтой аймаг.',
    short_desc: 'Зүүн монголын тал, Буйр нуур, Халхын гол',
    province: 'Дорнод',
    address: 'Чойбалсан хот, Дорнод аймаг',
    latitude: 48.0767,
    longitude: 114.5353,
    cover_image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800',
    is_published: true,
    is_featured: true,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Дундговь аймаг',
    type: 'nature',
    description: 'Дундговь аймаг нь Монгол Улсын төв өмнөд хэсэгт оршдог говийн аймаг. Говийн байгалийн үзэсгэлэн, Цагаан суварга, Хавцгайт хад чулуун зургийнхаа онцлогоор жуулчдыг татдаг.',
    short_desc: 'Говийн тал, Цагаан суварга, хавцгайт хад',
    province: 'Дундговь',
    address: 'Мандалговь хот, Дундговь аймаг',
    latitude: 45.7667,
    longitude: 106.2694,
    cover_image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
    is_published: true,
    is_featured: false,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Завхан аймаг',
    type: 'nature',
    description: 'Завхан аймаг нь Монгол Улсын баруун хэсэгт оршдог бөгөөд Хангайн нурууны баруун хэсгийг хамардаг. Отгонтэнгэр уул (4008м) нь Монгол Улсын хамгийн өндөр оргилуудын нэг бөгөөд энэ аймагт байдаг.',
    short_desc: 'Отгонтэнгэр уул, Хангайн баруун хэсэг, уулын аялал',
    province: 'Завхан',
    address: 'Улиастай хот, Завхан аймаг',
    latitude: 47.7400,
    longitude: 96.8444,
    cover_image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    is_published: true,
    is_featured: false,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Орхон аймаг',
    type: 'nature',
    description: 'Орхон аймаг нь Монгол Улсын хоёрдугаар том хот Эрдэнэттэй бөгөөд зэсийн уурхайгаараа дэлхийд алдартай. Орхоны хөндий, Эрдэнэт хотын орчимд байгалийн үзэсгэлэнт газрууд олон.',
    short_desc: 'Эрдэнэт хот, Орхоны хөндий, зэсийн уурхай',
    province: 'Орхон',
    address: 'Эрдэнэт хот, Орхон аймаг',
    latitude: 49.0278,
    longitude: 104.0444,
    cover_image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800',
    is_published: true,
    is_featured: false,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Өвөрхангай аймаг',
    type: 'nature',
    description: 'Өвөрхангай аймаг нь Монгол Улсын томоохон аймгуудын нэг бөгөөд Орхоны хөндийн дурсгалт газар дэлхийн өвд бүртгэгдсэн. Эрдэнэзуу хийд, Хархорин хот, Цэнхэрийн халуун рашаан зэрэг онцлог газруудтай.',
    short_desc: 'Орхоны хөндий, Эрдэнэзуу хийд, Хархорин',
    province: 'Өвөрхангай',
    address: 'Арвайхээр хот, Өвөрхангай аймаг',
    latitude: 46.2611,
    longitude: 102.7750,
    cover_image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    is_published: true,
    is_featured: true,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Өмнөговь аймаг',
    type: 'nature',
    description: 'Өмнөговь аймаг нь Говийн цөлийн гол хэсэгт оршдог. Хонгорын элс (дуулах элс), Баянзаг (Цахилгаант хад), Хэрмэн цав, динозаврын олдвор гарах газрууд нь дэлхийн жуулчдыг татдаг.',
    short_desc: 'Хонгорын дуулах элс, Баянзаг, динозаврын олдвор',
    province: 'Өмнөговь',
    address: 'Даланзадгад хот, Өмнөговь аймаг',
    latitude: 43.5706,
    longitude: 104.4250,
    cover_image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800',
    is_published: true,
    is_featured: true,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Сүхбаатар аймаг',
    type: 'nature',
    description: 'Сүхбаатар аймаг нь Монгол Улсын зүүн өмнөд хэсэгт оршдог говийн аймаг. Шилийн гол говь, Дариганга нутгийн онцгой байгаль, галт уулын гаралтай нуурууд нь жуулчдыг татдаг.',
    short_desc: 'Дариганга нутаг, галт уулын нуурууд, говийн байгаль',
    province: 'Сүхбаатар',
    address: 'Баруун-Урт хот, Сүхбаатар аймаг',
    latitude: 46.6806,
    longitude: 113.2806,
    cover_image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800',
    is_published: true,
    is_featured: false,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Сэлэнгэ аймаг',
    type: 'nature',
    description: 'Сэлэнгэ аймаг нь Монгол Улсын умард хэсэгт Оросын хилийн дагуу оршдог. Сэлэнгэ мөрний хөндий, ойн газрууд, Мандал сумын ойн амралтын цогцолборууд нь байгалийн аялалд тохиромжтой.',
    short_desc: 'Сэлэнгэ мөрөн, ойн газрууд, умардын байгаль',
    province: 'Сэлэнгэ',
    address: 'Сүхбаатар хот, Сэлэнгэ аймаг',
    latitude: 50.2389,
    longitude: 106.2083,
    cover_image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
    is_published: true,
    is_featured: false,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Төв аймаг',
    type: 'nature',
    description: 'Төв аймаг нь нийслэл Улаанбаатарыг тойрч оршдог бөгөөд Монгол Улсын хамгийн их жуулчин хүлээж авдаг аймгуудын нэг. Горхи-Тэрэлж үндэсний цэцэрлэгт хүрээлэн, Чингис хааны цогцолбор, Хустайн нуруу дархан цаазат газар зэрэг онцгой газруудтай.',
    short_desc: 'Тэрэлж, Хустайн тахь, Чингис хааны цогцолбор',
    province: 'Төв',
    address: 'Зуунмод хот, Төв аймаг',
    latitude: 47.7069,
    longitude: 106.9647,
    cover_image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    is_published: true,
    is_featured: true,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Увс аймаг',
    type: 'nature',
    description: 'Увс аймаг нь Монгол Улсын баруун умард хэсэгт оршдог. Увс нуур нь Монгол Улсын хамгийн том давстай нуур бөгөөд ЮНЕСКО-гийн дэлхийн өвд бүртгэгдсэн Увс нуурын сав газрын нэг хэсэг юм.',
    short_desc: 'Увс нуур — ЮНЕСКО дэлхийн өв, давстай нуур',
    province: 'Увс',
    address: 'Улаангом хот, Увс аймаг',
    latitude: 49.9806,
    longitude: 92.0639,
    cover_image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800',
    is_published: true,
    is_featured: true,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Ховд аймаг',
    type: 'nature',
    description: 'Ховд аймаг нь Монгол Улсын баруун хэсэгт Монгол Алтайн нурууны бэлд оршдог. Хар ус нуур, Монгол Алтайн Цаадах Говь дархан цаазат газар, Чандмань сумын агуй зэрэг байгалийн гайхамшгуудтай.',
    short_desc: 'Хар ус нуур, Монгол Алтай, баруун нутгийн байгаль',
    province: 'Ховд',
    address: 'Ховд хот, Ховд аймаг',
    latitude: 47.9944,
    longitude: 91.6417,
    cover_image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    is_published: true,
    is_featured: false,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Хөвсгөл аймаг',
    type: 'nature',
    description: 'Хөвсгөл аймаг нь "Монголын далай" хэмээн нэрлэгддэг Хөвсгөл нуураараа дэлхийд алдартай. Хөвсгөл нуур нь дэлхийн цэнгэг усны 0.4%-ийг агуулдаг бөгөөд Монгол Улсын хамгийн том байгалийн цогцолборуудын нэг.',
    short_desc: 'Хөвсгөл нуур — Монголын далай, ЮНЕСКО дэлхийн өв',
    province: 'Хөвсгөл',
    address: 'Мөрөн хот, Хөвсгөл аймаг',
    latitude: 49.6358,
    longitude: 100.1615,
    cover_image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    is_published: true,
    is_featured: true,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
  {
    name: 'Хэнтий аймаг',
    type: 'nature',
    description: 'Хэнтий аймаг нь Монгол Улсын зүүн умард хэсэгт оршдог бөгөөд Чингис хааны нутаг болох Хэнтийн нурууг хамардаг. Хан Хэнтийн Нуруу дархан цаазат газар, Балжийн гол, Онон-Балжийн үндэсний цэцэрлэгт хүрээлэн зэрэг газруудтай.',
    short_desc: 'Чингис хааны нутаг, Хэнтийн нуруу, Онон гол',
    province: 'Хэнтий',
    address: 'Чингис хот, Хэнтий аймаг',
    latitude: 47.3167,
    longitude: 110.6500,
    cover_image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
    is_published: true,
    is_featured: true,
    price_per_night: 0,
    rating_avg: 0,
    rating_count: 0,
    view_count: 0,
    images: [],
    amenities: [],
  },
];

async function seed() {
  const client = new MongoClient(MONGODB_URI);
  try {
    await client.connect();
    console.log('✅ MongoDB-д холбогдлоо');

    const db = client.db(DB_NAME);
    const collection = db.collection('places');

    // Existing аймгуудыг шалгах
    const existing = await collection.countDocuments({ type: 'nature', province: { $in: aimags.map(a => a.province) } });
    if (existing > 0) {
      console.log(`⚠️  ${existing} аймаг аль хэдийн байна. Дахин оруулахгүй.`);
      console.log('Устгаж дахин оруулахын тулд MongoDB Compass дээр places collection-г цэвэрлэнэ үү.');
      return;
    }

    const now = new Date();
    const docs = aimags.map(a => ({
      ...a,
      createdAt: now,
      updatedAt: now,
    }));

    const result = await collection.insertMany(docs);
    console.log(`🎉 ${result.insertedCount} аймгийн өгөгдөл амжилттай оруулагдлаа!`);
    console.log('\n📍 Оруулсан аймгууд:');
    aimags.forEach((a, i) => console.log(`  ${i + 1}. ${a.name} (${a.province})`));

  } catch (err) {
    console.error('❌ Алдаа:', err.message);
  } finally {
    await client.close();
    console.log('\n🔌 MongoDB холболт хаагдлаа');
  }
}

seed();
